// @generated by protoc-gen-connect-es v0.10.1
// @generated from file shitlist/v1/shitlist.proto (package shitlist.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClickRequest, ClickResponse, LeadersRequest, LeadersResponse } from "./shitlist_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ShitlistService provides shitty service.
 *
 * @generated from service shitlist.v1.ShitlistService
 */
export const ShitlistService = {
  typeName: "shitlist.v1.ShitlistService",
  methods: {
    /**
     * Click records a click action by a user.
     *
     * @generated from rpc shitlist.v1.ShitlistService.Click
     */
    click: {
      name: "Click",
      I: ClickRequest,
      O: ClickResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Leaders returns the top 10 clickers.
     *
     * @generated from rpc shitlist.v1.ShitlistService.Leaders
     */
    leaders: {
      name: "Leaders",
      I: LeadersRequest,
      O: LeadersResponse,
      kind: MethodKind.Unary,
    },
  }
};

