// @generated by protoc-gen-es v1.2.1
// @generated from file shitlist/v1/shitlist.proto (package shitlist.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * ClickRequest is a request to record a click event.
 *
 * @generated from message shitlist.v1.ClickRequest
 */
export const ClickRequest = proto3.makeMessageType(
  "shitlist.v1.ClickRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ClickResponse is a response to a click event.
 *
 * @generated from message shitlist.v1.ClickResponse
 */
export const ClickResponse = proto3.makeMessageType(
  "shitlist.v1.ClickResponse",
  () => [
    { no: 1, name: "clicks", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * LeadersRequest is a request for the top clickers.
 *
 * @generated from message shitlist.v1.LeadersRequest
 */
export const LeadersRequest = proto3.makeMessageType(
  "shitlist.v1.LeadersRequest",
  [],
);

/**
 * Clicker represents a single clicker user.
 *
 * @generated from message shitlist.v1.Clicker
 */
export const Clicker = proto3.makeMessageType(
  "shitlist.v1.Clicker",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "clicks", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * LeadersResponse is the top clickers.
 *
 * @generated from message shitlist.v1.LeadersResponse
 */
export const LeadersResponse = proto3.makeMessageType(
  "shitlist.v1.LeadersResponse",
  () => [
    { no: 1, name: "top_clickers", kind: "message", T: Clicker, repeated: true },
  ],
);

