// @generated by protoc-gen-connect-es v0.10.1
// @generated from file shitlist/v1/shitlist.proto (package shitlist.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClickRequest, ClickResponse, LeadersRequest, LeadersResponse } from "./shitlist_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ShitlistService provides shitty service.
 *
 * @generated from service shitlist.v1.ShitlistService
 */
export declare const ShitlistService: {
  readonly typeName: "shitlist.v1.ShitlistService",
  readonly methods: {
    /**
     * Click records a click action by a user.
     *
     * @generated from rpc shitlist.v1.ShitlistService.Click
     */
    readonly click: {
      readonly name: "Click",
      readonly I: typeof ClickRequest,
      readonly O: typeof ClickResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Leaders returns the top 10 clickers.
     *
     * @generated from rpc shitlist.v1.ShitlistService.Leaders
     */
    readonly leaders: {
      readonly name: "Leaders",
      readonly I: typeof LeadersRequest,
      readonly O: typeof LeadersResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

