name: proto
on:
  pull_request:
jobs:
  lint:
    name: buf/lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.3.1
      - uses: bufbuild/buf-lint-action@v0.3.0
  breaking:
    name: buf/breaking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.3.1
      - uses: bufbuild/buf-breaking-action@v0.4.0
        with:
          against: 'https://github.com/BethesdaNet/apis.git#branch=main'